blank_issues_enabled: false
contact_links:
    - name: ‚ùì Questions, Help, and Advice
      url: https://github.com/ganemedelabs/anso/discussions
      about: For general support, please refer to our discussion board for questions, help, or advice.
